<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy — Sentient Brewer</title>
    <link rel="stylesheet" href="/assets/style.css">
    <style>
        .policy { max-width: 800px; margin: 0 auto; padding: 40px 20px; line-height: 1.8; }
        .policy h1 { color: var(--brass); margin-bottom: 8px; }
        .policy h2 { color: var(--brass); margin-top: 30px; margin-bottom: 10px; font-size: 18px; }
        .policy p, .policy li { color: var(--text); margin-bottom: 12px; }
        .policy ul { padding-left: 24px; }
        .policy a { color: var(--brass); }
        .policy .updated { color: var(--text-dim); font-size: 13px; margin-bottom: 30px; }
    </style>
</head>
<body>
    <div class="policy">
        <h1>Privacy Policy</h1>
        <p class="updated">Last updated: March 21, 2026</p>

        <p>Sentient Brewer ("we", "us", "our") is operated by Sentient Bean / Will The Bard. This policy describes how we collect, use, and protect your information when you use our service at sentientbrewer.com.</p>

        <h2>1. Information We Collect</h2>
        <p><strong>Account Information:</strong> When you register, we collect your email address, name, and a hashed password. We never store your password in plain text.</p>
        <p><strong>Project Data:</strong> We store the project descriptions you submit, the code generated by our AI agents, agent run logs, and compiled output files.</p>
        <p><strong>Usage Data:</strong> We track token usage and agent run counts for billing and system monitoring purposes. We do not use third-party analytics or tracking scripts.</p>

        <h2>2. How We Use Your Information</h2>
        <ul>
            <li>To authenticate your account and provide access to the service</li>
            <li>To process your project descriptions through the Anthropic Claude API for code generation</li>
            <li>To compile, sign, and deliver executable files you request</li>
            <li>To monitor system usage, costs, and performance</li>
            <li>To communicate with you about your account if necessary</li>
        </ul>

        <h2>3. Third-Party Services</h2>
        <p>We use the following third-party services to provide our functionality:</p>
        <ul>
            <li><strong>Anthropic (Claude API):</strong> Your project descriptions and generated code are sent to Anthropic's API for AI processing. Anthropic's privacy policy applies to data processed by their service. Anthropic does not use API inputs to train their models.</li>
            <li><strong>SignPath.io:</strong> Compiled executables are submitted to SignPath for code signing. Only the compiled binary is transmitted, not your source code or personal information.</li>
        </ul>

        <h2>4. Data Sharing</h2>
        <p>We do not sell, rent, or share your personal information with third parties for marketing purposes. We only share data with the third-party services listed above as necessary to provide the service.</p>

        <h2>5. Open Source Projects</h2>
        <p>Source code generated by Sentient Brewer may be published to public GitHub repositories for open source code signing purposes. By using the service, you acknowledge that generated code may be made publicly available under the MIT license.</p>

        <h2>6. Data Retention</h2>
        <p>Your account data and project files are retained as long as your account is active. You may request deletion of your account and all associated data by contacting us. Upon deletion, all project files, generated code, and compiled outputs are permanently removed.</p>

        <h2>7. Data Security</h2>
        <p>We protect your data using:</p>
        <ul>
            <li>HTTPS/TLS encryption for all data in transit</li>
            <li>Argon2ID password hashing</li>
            <li>JWT-based stateless authentication</li>
            <li>Server-side access controls and input sanitization</li>
        </ul>

        <h2>8. Your Rights</h2>
        <p>You have the right to:</p>
        <ul>
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your account and data</li>
            <li>Download your generated project files at any time</li>
        </ul>

        <h2>9. Children's Privacy</h2>
        <p>Sentient Brewer is not directed at children under 13. We do not knowingly collect personal information from children under 13.</p>

        <h2>10. Changes to This Policy</h2>
        <p>We may update this privacy policy from time to time. Changes will be posted on this page with an updated date.</p>

        <h2>11. Contact</h2>
        <p>For privacy-related questions or data requests, contact us at:</p>
        <p>Email: <a href="mailto:willthebard0@gmail.com">willthebard0@gmail.com</a><br>
        Web: <a href="https://sentientbean.net">sentientbean.net</a></p>

        <hr style="border-color: var(--border); margin: 40px 0 20px;">
        <p style="text-align: center;"><a href="/">&#8592; Back to Sentient Brewer</a></p>
    </div>
</body>
</html>
